"""TestOps project 5276 — @allure.id values keyed by pytest nodeid."""
from __future__ import annotations

# Sync: curl TestOps /api/rs/testcase?projectId=5276 + fuzzy match by title/function name.
TESTOPS_IDS: dict[str, str] = {
    'tests/test_budget.py::test_format_savings_lines': '45908',
    'tests/test_budget.py::test_format_tool_footer_cursor_no_savings': '45851',
    'tests/test_budget.py::test_format_tool_footer_detailed_breakdown': '45879',
    'tests/test_budget.py::test_wrap_mcp_response_appends_footer': '45904',
    'tests/test_cli.py::test_cli_help': '45888',
    'tests/test_cli.py::test_cli_pipeline_list': '45911',
    'tests/test_cli.py::test_cli_route_tool': '45840',
    'tests/test_cli_commands.py::test_cli_audit_context': '45873',
    'tests/test_cli_commands.py::test_cli_config_init': '45891',
    'tests/test_cli_commands.py::test_cli_rag_query': '45900',
    'tests/test_cli_commands.py::test_cli_scripts_list': '45911',
    'tests/test_code_search.py::test_resolve_search_path_by_filename': '45893',
    'tests/test_code_search.py::test_resolve_search_path_in_minimal_workspace': '45893',
    'tests/test_code_search.py::test_search_code_finds_in_minimal_workspace': '45885',
    'tests/test_code_search.py::test_search_code_global_finds_baseurl': '45912',
    'tests/test_code_search.py::test_search_code_scoped_file_no_match': '45855',
    'tests/test_context_audit.py::test_audit_context_finds_rules': '45873',
    'tests/test_context_audit.py::test_render_audit_includes_totals': '45864',
    'tests/test_estimator.py::test_cursor_saved_for_tool_tier': '45880',
    'tests/test_executors.py::test_execute_task_cursor_returns_empty': '45863',
    'tests/test_executors.py::test_execute_task_rag_fallback_on_weak_rg': '45878',
    'tests/test_mcp_icon.py::test_mcp_icons_advertises_png_data_uri': '45868',
    'tests/test_mcp_tools.py::test_mcp_pipeline_list_recipes': '45911',
    'tests/test_pipeline.py::test_format_pipeline_footer_has_by_executor': '45884',
    'tests/test_pipeline.py::test_parse_custom_chain': '45875',
    'tests/test_pipeline.py::test_parse_named_pipeline_meta_audit': '45829',
    'tests/test_pipeline.py::test_parse_named_pipeline_search_rag_reuses_query': '45834',
    'tests/test_pipeline.py::test_pipeline_dry_run': '45901',
    'tests/test_pipeline.py::test_pipeline_execute_skips_unavailable_ollama': '45845',
    'tests/test_pipeline.py::test_pipeline_stops_on_error': '45846',
    'tests/test_prompt_compress.py::test_compress_heuristic_drops_filler_lines': '45844',
    'tests/test_prompt_compress.py::test_compress_prompt_detail_heuristic': '45881',
    'tests/test_prompt_compress.py::test_format_dual_wraps_blocks': '45887',
    'tests/test_pyramid_layers.py::test_every_test_module_has_pyramid_layer': '45915',
    'tests/test_pyramid_layers.py::test_layer_mapping_counts': '45916',
    'tests/test_rag_index.py::test_get_indexed_chunks_caches': '45838',
    'tests/test_rag_index.py::test_index_invalidates_on_chunk_edit': '45886',
    'tests/test_rag_index.py::test_search_rag_still_finds_baseurl': '45839',
    'tests/test_rag_index.py::test_search_reads_only_top_hits': '45866',
    'tests/test_rag_search.py::test_format_hits_empty': '45860',
    'tests/test_rag_search.py::test_format_hits_includes_excerpt': '45843',
    'tests/test_rag_search.py::test_search_rag_empty_query': '45900',
    'tests/test_rag_search.py::test_search_rag_finds_baseurl': '45853',
    'tests/test_rag_search.py::test_search_rag_no_manifest': '45850',
    'tests/test_rag_tokens.py::test_rag_est_tokens_reuses_body_without_reread': '45841',
    'tests/test_router.py::test_route_cursor_fallback': '45852',
    'tests/test_router.py::test_route_find_goes_to_tool': '45847',
    'tests/test_router.py::test_route_rag_question': '45836',
    'tests/test_router.py::test_route_skips_unavailable_ollama': '45845',
    'tests/test_router.py::test_route_task_all_tiers_has_five_rows': '45832',
    'tests/test_search.py::test_build_tool_command_uses_identifier_not_phrase': '45871',
    'tests/test_search.py::test_extract_search_query[find baseUrl in test config-baseUrl]': '45910',
    'tests/test_search.py::test_extract_search_query[find baseUrl in configurator presets-baseUrl]': '45910',
    'tests/test_search.py::test_extract_search_query[find phase-manifest.json-phase-manifest.json]': '45910',
    'tests/test_search.py::test_extract_search_query[grep for ConfigReader in tests-ConfigReader]': '45910',
    'tests/test_search.py::test_extract_search_query[search for "healthCheck path"-healthCheck path]': '45910',
    'tests/test_search.py::test_filter_tool_output_drops_hooks_readme': '45865',
    'tests/test_search.py::test_tool_output_weak_when_empty': '45869',
    'tests/test_security.py::test_build_tool_command_quotes_root': '45907',
    'tests/test_security.py::test_mcp_pipeline_dry_run_by_default': '45837',
    'tests/test_security.py::test_ollama_available_uses_cache': '45859',
    'tests/test_security.py::test_resolve_wrapper_command_quotes_root_and_args': '45830',
    'tests/test_security.py::test_root_cd_prefix_quotes_spaces': '45882',
    'tests/test_security.py::test_shell_args_quotes_metacharacters': '45831',
    'tests/test_settings.py::test_defaults_without_config': '45867',
    'tests/test_settings.py::test_env_overrides_files': '45858',
    'tests/test_settings.py::test_format_shell_export': '45906',
    'tests/test_settings.py::test_init_user_config': '45891',
    'tests/test_settings.py::test_workspace_config_overrides_user': '45889',
    'tests/test_settings.py::test_workspace_config_path': '45895',
    'tests/test_tokens.py::test_collect_paths_skips_git': '45876',
    'tests/test_tokens.py::test_count_texts_batch_matches_single': '45856',
    'tests/test_tokens.py::test_count_tokens_uses_tiktoken': '45872',
    'tests/test_tool_output.py::test_filter_tool_output_strips_blank_lines': '45896',
    'tests/test_tool_output.py::test_version_matches_pyproject': '45890',
    'tests/test_tool_paths.py::test_resolve_rg_finds_cursor_bundle': '45894',
    'tests/test_tool_paths.py::test_search_code_works_without_path_env': '45909',
    'tests/test_usage.py::test_aggregate_by_tier': '45914',
    'tests/test_usage.py::test_append_event': '45902',
    'tests/test_usage.py::test_append_failure': '45854',
    'tests/test_usage.py::test_append_rotates_before_write': '45902',
    'tests/test_usage.py::test_build_route_event_truncates_task': '45913',
    'tests/test_usage.py::test_cursor_baseline_includes_overhead': '45870',
    'tests/test_usage.py::test_cursor_saved_cursor': '45898',
    'tests/test_usage.py::test_cursor_saved_tool': '45880',
    'tests/test_usage.py::test_format_report_empty': '45860',
    'tests/test_usage.py::test_load_events_reads_archives': '45897',
    'tests/test_usage.py::test_load_events_skips_bad_lines': '45833',
    'tests/test_usage.py::test_log_archive_paths_order': '45874',
    'tests/test_usage.py::test_logging_disabled': '45842',
    'tests/test_usage.py::test_max_log_bytes_env': '45862',
    'tests/test_usage.py::test_parse_since_variants': '45903',
    'tests/test_usage.py::test_rotate_log_keeps_archives': '45835',
    'tests/test_usage.py::test_rotate_log_when_over_limit': '45892',
    'tests/test_wrappers.py::test_ollama_available_against_stub': '45849',
    'tests/test_wrappers.py::test_ollama_available_false': '45905',
    'tests/test_wrappers.py::test_ollama_available_true': '45849',
    'tests/test_wrappers.py::test_resolve_wrapper_command_python': '45877',
    'tests/test_wrappers.py::test_resolve_wrapper_unknown_raises': '45877',
    'tests/test_wrappers.py::test_wrappers_registry_has_check_meta_sync': '45899',
}
